package com.trig.api.quests;

/**
  Lots of quests in this game.
*/
enum Quests {
A_HUNTERS_CALLING("A Hunter's Calling"),
POINT_OF_NO_RETURN("Point of No Return"),
A_JOURNEY_FURTHER("A Journey Further"),
A_JOURNEY_BEYOND("A Journey Beyond"),
THE_OLMIC_RUNE("The Olmic Rune"),
MINIQUEST_SLAY_DRAGONLINGS("Mini-Quest - Slay Dragonlings"),
THE_HERO_OF_GAVEL("The Hero of Gavel"),
MINIQUEST_SLAY_ANGELS("Mini-Quest - Slay Angels"),
ROYAL_TRIALS("Royal Trials"),
MINIQUEST_SLAY_CONURES("Mini-Quest - Slay Conures"),
THE_FORTUNETELLER("The Fortuneteller"),
RECIPE_FOR_DISASTER("Recipe For Disaster"),
MINIQUEST_SLAY_CREATURES_OF_THE_VOID("Mini-Quest - Slay Creatures of the Void"),
ONE_THOUSAND_METERS_UNDER("One Thousand Meters Under"),
MINIQUEST_SLAY_ASTROCHELYS_MANIS("Mini-Quest - Slay Astrochelys Manis"),
DWARVES_AND_DOGUNS_PART_IV("Dwarves and Doguns Part IV"),
MINIQUEST_SLAY_IFRITS("Mini-Quest - Slay Ifrits"),
DWARVES_AND_DOGUNS_PART_III("Dwarves and Doguns Part III"),
THE_FEATHERS_FLY_PART_II("The Feathers Fly Part II"),
MINIQUEST_SLAY_AZERS("Mini-Quest - Slay Azers"),
DWARVES_AND_DOGUNS_PART_II("Dwarves and Doguns Part II"),
MINIQUEST_SLAY_FROSTED_GUARDS_CRYOSTONE_GOLEMS("Mini-Quest - Slay Frosted Guards AND Cryostone Golems"),
THE_FEATHERS_FLY_PART_I("The Feathers Fly Part I"),
DWARVES_AND_DOGUNS_PART_I("Dwarves and Doguns Part I"),
MINIQUEST_SLAY_MAGMA_ENTITIES("Mini-Quest - Slay Magma Entities"),
MINIQUEST_SLAY_PERNIX_MONKEYS("Mini-Quest - Slay Pernix Monkeys"),
FANTASTIC_VOYAGE("Fantastic Voyage"),
THE_ENVOY_PART_II("The Envoy Part II"),
ENTER_THE_DOJO("Enter the Dojo"),
THE_HIDDEN_CITY("The Hidden City"),
MINIQUEST_SLAY_AILUROPODAS("Mini-Quest - Slay Ailuropodas"),
BEYOND_THE_GRAVE("Beyond the Grave"),
MIXED_FEELINGS("Mixed Feelings"),
COWFUSION("Cowfusion"),
DESPERATE_METAL("Desperate Metal"),
THE_CANARY_CALLS("The Canary Calls"),
THE_LOST("The Lost"),
MINIQUEST_SLAY_ROBOTS("Mini-Quest - Slay Robots"),
THE_CANYON_GUIDES("The Canyon Guides"),
A_MARAUDERS_DUES("A Marauder's Dues"),
THE_ENVOY_PART_I("The Envoy Part I"),
MINIQUEST_SLAY_JINKOS("Mini-Quest - Slay Jinkos"),
THE_BELLY_OF_THE_BEAST("The Belly of the Beast"),
THE_THANOS_VAULTS("The Thanos Vaults"),
FROM_THE_BOTTOM("From the Bottom"),
GENERALS_ORDERS("General's Orders"),
MINIQUEST_SLAY_HOBGOBLINS("Mini-Quest - Slay Hobgoblins"),
THE_QIRA_HIVE("The Qira Hive"),
TRIPLE_QUESTION_MARK("???"),
FALLEN_DELIVERY("Fallen Delivery"),
REALM_OF_LIGHT_V__THE_REALM_OF_LIGHT("Realm of Light V - The Realm of Light"),
THE_HUNGER_OF_GERTS_PART_2("The Hunger of Gerts Part 2"),
MINIQUEST_SLAY_FELROCS("Mini-Quest - Slay Felrocs"),
PURPLE_AND_BLUE("Purple and Blue"),
THE_HUNGER_OF_GERTS_PART_1("The Hunger of Gerts Part 1"),
THE_BIGGER_PICTURE("The Bigger Picture"),
ALDOREIS_SECRET_PART_II("Aldorei's Secret Part II"),
FLIGHT_IN_DISTRESS("Flight in Distress"),
THE_ULTIMATE_WEAPON("The Ultimate Weapon"),
MINIQUEST_SLAY_WEIRDS("Mini-Quest - Slay Weirds"),
ACQUIRING_CREDENTIALS("Acquiring Credentials"),
REINCARNATION("Reincarnation"),
ALDOREIS_SECRET_PART_I("Aldorei's Secret Part I"),
TROUBLED_TRIBESMEN("Troubled Tribesmen"),
MURDER_MYSTERY("Murder Mystery"),
MINIQUEST_SLAY_MYCONIDS("Mini-Quest - Slay Myconids"),
LEXDALE_WITCH_TRIALS("Lexdale Witch Trials"),
FORBIDDEN_PRISON("Forbidden Prison"),
REALM_OF_LIGHT_IV__FINDING_THE_LIGHT("Realm of Light IV - Finding the Light"),
HAVEN_ANTIQUITY("Haven Antiquity"),
WYNNEXCAVATION_SITE_D("WynnExcavation Site D"),
SHATTERED_MINDS("Shattered Minds"),
MINIQUEST_SLAY_DEAD_VILLAGERS("Mini-Quest - Slay Dead Villagers"),
LAZARUS_PIT("Lazarus Pit"),
GRAND_YOUTH("Grand Youth"),
TEMPLE_OF_THE_LEGENDS("Temple of the Legends"),
FROM_THE_MOUNTAINS("From the Mountains"),
MEMORY_PARANOIA("Memory Paranoia"),
LOST_SOLES("Lost Soles"),
LOST_ROYALTY("Lost Royalty"),
MINIQUEST_SLAY_IDOLS("Mini-Quest - Slay Idols"),
REALM_OF_LIGHT_III__A_HEADLESS_HISTORY("Realm of Light III - A Headless History"),
OUT_OF_MY_MIND("Out of my Mind"),
LOST_IN_THE_JUNGLE("Lost in the Jungle"),
REALM_OF_LIGHT_II__TAPROOT("Realm of Light II - Taproot"),
REDBEARDS_BOOTY("Redbeard's Booty"),
RECLAIMING_THE_HOUSE("Reclaiming the House"),
MINIQUEST_SLAY_WRAITHS_AND_PHANTASMS("Mini-Quest - Slay Wraiths & Phantasms"),
BENEATH_THE_DEPTHS("Beneath the Depths"),
THE_ORDER_OF_THE_GROOK("The Order of the Grook"),
AN_IRON_HEART_PART_II("An Iron Heart Part II"),
THE_PASSAGE("The Passage"),
ZHIGHT_ISLAND("Zhight Island"),
WYNNEXCAVATION_SITE_C("WynnExcavation Site C"),
MINIQUEST_SLAY_LIZARDMEN("Mini-Quest - Slay Lizardmen"),
REALM_OF_LIGHT_I__THE_WORM_HOLES("Realm of Light I - The Worm Holes"),
THE_SHADOW_OF_THE_BEAST("The Shadow of the Beast"),
DEATH_WHISTLE("Death Whistle"),
MASTER_PIECE("Master Piece"),
JUNGLE_FEVER("Jungle Fever"),
CORRUPTED_BETRAYAL("Corrupted Betrayal"),
CROP_FAILURE("Crop Failure"),
THE_MAIDEN_TOWER("The Maiden Tower"),
A_GRAVE_MISTAKE("A Grave Mistake"),
MINIQUEST_SLAY_SLIMES("Mini-Quest - Slay Slimes"),
RISE_OF_THE_QUARTRON("Rise of the Quartron"),
AN_IRON_HEART_PART_I("An Iron Heart Part I"),
THE_HOUSE_OF_TWAIN("The House of Twain"),
FROST_BITE("Frost Bite"),
WYNNEXCAVATION_SITE_B("WynnExcavation Site B"),
BOBS_LOST_SOUL("Bob's Lost Soul"),
MINIQUEST_SLAY_ORCS("Mini-Quest - Slay Orcs"),
BLAZING_RETRIBUTION("Blazing Retribution"),
FATE_OF_THE_FALLEN("Fate of the Fallen"),
UNDERICE("Underice"),
STAR_THIEF("Star Thief"),
CLEARING_THE_CAMPS("Clearing the Camps"),
HEART_OF_LLEVIGAR("Heart of Llevigar"),
MINIQUEST_SLAY_CREATURES_OF_NESAAK_FOREST("Mini-Quest - Slay Creatures of Nesaak Forest"),
ICE_NATIONS("Ice Nations"),
TOWER_OF_ASCENSION("Tower of Ascension"),
PIRATES_TROVE("Pirate's Trove"),
CANYON_CONDOR("Canyon Condor"),
WRATH_OF_THE_MUMMY("Wrath of the Mummy"),
WYNNEXCAVATION_SITE_A("WynnExcavation Site A"),
TRIBAL_AGGRESSION("Tribal Aggression"),
MINIQUEST_SLAY_COYOTES("Mini-Quest - Slay Coyotes"),
KINGDOM_OF_SAND("Kingdom of Sand"),
MEANINGFUL_HOLIDAY("Meaningful Holiday"),
A_SANDY_SCANDAL("A Sandy Scandal"),
GREEN_GLOOP("Green Gloop"),
MINIQUEST_SLAY_SCARABS("Mini-Quest - Slay Scarabs"),
THE_MERCENARY("The Mercenary"),
CRAFTMAS_CHAOS("Craftmas Chaos"),
MISADVENTURE_ON_THE_SEA("Misadventure on the Sea"),
DEJA_VU("Deja Vu"),
THE_CORRUPTED_VILLAGE("The Corrupted Village"),
LOST_TOWER("Lost Tower"),
MINIQUEST_SLAY_SKELETONS("Mini-Quest - Slay Skeletons"),
RECOVER_THE_PAST("Recover the Past"),
THE_DARK_DESCENT("The Dark Descent"),
DWELLING_WALLS("Dwelling Walls"),
CLUCK_CLUCK("Cluck Cluck"),
PIT_OF_THE_DEAD("Pit of the Dead"),
STUDYING_THE_CORRUPT("Studying the Corrupt"),
MACABRE_MASQUERADE_HALLOWYNN_2014("Macabre Masquerade ''Hallowynn 2014''"),
GRAVE_DIGGER("Grave Digger"),
MALTICS_WELL("Maltic's Well"),
MINIQUEST_SLAY_MOOSHROOMS("Mini-Quest - Slay Mooshrooms"),
CREEPER_INFILTRATION("Creeper Infiltration"),
ARACHNIDS_ASCENT("Arachnids' Ascent"),
STABLE_STORY("Stable Story"),
POTION_MAKING("Potion Making"),
ELEMENTAL_EXERCISE("Elemental Exercise"),
MUSHROOM_MAN("Mushroom Man"),
UNDERWATER("Underwater"),
TUNNEL_TROUBLE("Tunnel Trouble"),
THE_SEWERS_OF_RAGNI("The Sewers of Ragni"),
INFESTED_PLANTS("Infested Plants"),
MINIQUEST_SLAY_SPIDERS("Mini-Quest - Slay Spiders"),
COOK_ASSISTANT("Cook Assistant"),
POISONING_THE_PEST("Poisoning the Pest"),
KINGS_RECRUIT("King's Recruit"),
MINIQUEST_GATHER_GUDGEON("Mini-Quest - Gather Gudgeon"),
MINIQUEST_GATHER_WHEAT("Mini-Quest - Gather Wheat"),
ENZANS_BROTHER("Enzan's Brother"),
MINIQUEST_GATHER_ICEFISH_II("Mini-Quest - Gather Icefish II"),
MINIQUEST_GATHER_LIGHT_LOGS("Mini-Quest - Gather Light Logs"),
MINIQUEST_GATHER_LIGHT_LOGS_II("Mini-Quest - Gather Light Logs II"),
MINIQUEST_GATHER_KANDERSTONE("Mini-Quest - Gather Kanderstone"),
MINIQUEST_GATHER_KANDERSTONE_II("Mini-Quest - Gather Kanderstone II"),
MINIQUEST_GATHER_LIGHT_LOGS_III("Mini-Quest - Gather Light Logs III"),
MINIQUEST_GATHER_DECAY_ROOTS_III("Mini-Quest - Gather Decay Roots III"),
MINIQUEST_GATHER_DECAY_ROOTS_II("Mini-Quest - Gather Decay Roots II"),
MINIQUEST_GATHER_DECAY_ROOTS("Mini-Quest - Gather Decay Roots"),
MINIQUEST_GATHER_KANDERSTONE_III("Mini-Quest - Gather Kanderstone III"),
MINIQUEST_GATHER_DIAMONDS("Mini-Quest - Gather Diamonds"),
MINIQUEST_GATHER_DIAMONDS_IV("Mini-Quest - Gather Diamonds IV"),
MINIQUEST_GATHER_DIAMONDS_II("Mini-Quest - Gather Diamonds II"),
MINIQUEST_GATHER_DIAMONDS_III("Mini-Quest - Gather Diamonds III"),
MINIQUEST_GATHER_PINE_LOGS_II("Mini-Quest - Gather Pine Logs II"),
MINIQUEST_GATHER_PINE_LOGS("Mini-Quest - Gather Pine Logs"),
MINIQUEST_GATHER_BAMBOO("Mini-Quest - Gather Bamboo"),
MINIQUEST_GATHER_PINE_LOGS_III("Mini-Quest - Gather Pine Logs III"),
MINIQUEST_GATHER_RICE_III("Mini-Quest - Gather Rice III"),
MINIQUEST_GATHER_RICE_II("Mini-Quest - Gather Rice II"),
MINIQUEST_GATHER_RICE("Mini-Quest - Gather Rice"),
MINIQUEST_GATHER_RICE_IV("Mini-Quest - Gather Rice IV"),
MINIQUEST_GATHER_AVO_LOGS_II("Mini-Quest - Gather Avo Logs II"),
MINIQUEST_GATHER_MOLTEN_ORE_III("Mini-Quest - Gather Molten Ore III"),
MINIQUEST_GATHER_AVO_LOGS("Mini-Quest - Gather Avo Logs"),
MINIQUEST_GATHER_AVO_LOGS_III("Mini-Quest - Gather Avo Logs III"),
MINIQUEST_GATHER_AVO_LOGS_IV("Mini-Quest - Gather Avo Logs IV"),
MINIQUEST_GATHER_SORGHUM("Mini-Quest - Gather Sorghum"),
MINIQUEST_GATHER_SORGHUM_II("Mini-Quest - Gather Sorghum II"),
MINIQUEST_GATHER_COPPER("Mini-Quest - Gather Copper"),
MINIQUEST_GATHER_GRANITE("Mini-Quest - Gather Granite"),
MINIQUEST_GATHER_BARLEY("Mini-Quest - Gather Barley"),
MINIQUEST_GATHER_OAK_LOGS("Mini-Quest - Gather Oak Logs"),
MINIQUEST_GATHER_TROUT("Mini-Quest - Gather Trout"),
MINIQUEST_GATHER_BIRCH_LOGS("Mini-Quest - Gather Birch Logs"),
MINIQUEST_GATHER_GOLD("Mini-Quest - Gather Gold"),
MINIQUEST_GATHER_GOLD_II("Mini-Quest - Gather Gold II"),
MINIQUEST_GATHER_CARP_II("Mini-Quest - Gather Carp II"),
MINIQUEST_GATHER_MALT_II("Mini-Quest - Gather Malt II"),
MINIQUEST_GATHER_ACACIA_LOGS_II("Mini-Quest - Gather Acacia Logs II"),
MINIQUEST_GATHER_OATS_II("Mini-Quest - Gather Oats II"),
MINIQUEST_GATHER_ACACIA_LOGS("Mini-Quest - Gather Acacia Logs"),
MINIQUEST_GATHER_SALMON_II("Mini-Quest - Gather Salmon II"),
MINIQUEST_GATHER_SALMON("Mini-Quest - Gather Salmon"),
MINIQUEST_GATHER_WILLOW_LOGS_II("Mini-Quest - Gather Willow Logs II"),
MINIQUEST_GATHER_WILLOW_LOGS("Mini-Quest - Gather Willow Logs"),
MINIQUEST_GATHER_OATS("Mini-Quest - Gather Oats"),
MINIQUEST_GATHER_SANDSTONE_II("Mini-Quest - Gather Sandstone II"),
MINIQUEST_GATHER_SANDSTONE("Mini-Quest - Gather Sandstone"),
MINIQUEST_GATHER_CARP("Mini-Quest - Gather Carp"),
MINIQUEST_GATHER_MALT("Mini-Quest - Gather Malt"),
MINIQUEST_GATHER_SPRUCE_LOGS("Mini-Quest - Gather Spruce Logs"),
MINIQUEST_GATHER_SPRUCE_LOGS_II("Mini-Quest - Gather Spruce Logs II"),
MINIQUEST_GATHER_ICEFISH("Mini-Quest - Gather Icefish"),
MINIQUEST_GATHER_JUNGLE_LOGS("Mini-Quest - Gather Jungle Logs"),
MINIQUEST_GATHER_JUNGLE_LOGS_II("Mini-Quest - Gather Jungle Logs II"),
MINIQUEST_GATHER_PIRANHAS_II("Mini-Quest - Gather Piranhas II"),
MINIQUEST_GATHER_PIRANHAS("Mini-Quest - Gather Piranhas"),
MINIQUEST_GATHER_KOI_II("Mini-Quest - Gather Koi II"),
MINIQUEST_GATHER_KOI("Mini-Quest - Gather Koi"),
MINIQUEST_GATHER_COBALT("Mini-Quest - Gather Cobalt"),
MINIQUEST_GATHER_IRON_II("Mini-Quest - Gather Iron II"),
MINIQUEST_GATHER_IRON("Mini-Quest - Gather Iron"),
MINIQUEST_GATHER_DARK_LOGS_III("Mini-Quest - Gather Dark Logs III"),
MINIQUEST_GATHER_HOPS("Mini-Quest - Gather Hops"),
MINIQUEST_GATHER_HOPS_II("Mini-Quest - Gather Hops II"),
MINIQUEST_GATHER_SILVER("Mini-Quest - Gather Silver"),
MINIQUEST_GATHER_RYE_II("Mini-Quest - Gather Rye II"),
MINIQUEST_GATHER_RYE("Mini-Quest - Gather Rye"),
MINIQUEST_GATHER_KOI_III("Mini-Quest - Gather Koi III"),
MINIQUEST_GATHER_DARK_LOGS_II("Mini-Quest - Gather Dark Logs II"),
MINIQUEST_GATHER_DARK_LOGS("Mini-Quest - Gather Dark Logs"),
MINIQUEST_GATHER_COBALT_II("Mini-Quest - Gather Cobalt II"),
MINIQUEST_GATHER_MILLET("Mini-Quest - Gather Millet"),
MINIQUEST_GATHER_MILLET_II("Mini-Quest - Gather Millet II"),
MINIQUEST_GATHER_MILLET_III("Mini-Quest - Gather Millet III"),
MINIQUEST_GATHER_COBALT_III("Mini-Quest - Gather Cobalt III"),
MINIQUEST_GATHER_BASS_II("Mini-Quest - Gather Bass II"),
MINIQUEST_GATHER_BASS_III("Mini-Quest - Gather Bass III"),
MINIQUEST_GATHER_BASS_IV("Mini-Quest - Gather Bass IV"),
MINIQUEST_GATHER_BASS("Mini-Quest - Gather Bass"),
MINIQUEST_GATHER_SILVER_II("Mini-Quest - Gather Silver II"),
MINIQUEST_GATHER_GYLIA_FISH("Mini-Quest - Gather Gylia Fish"),
MINIQUEST_GATHER_GYLIA_FISH_II("Mini-Quest - Gather Gylia Fish II"),
MINIQUEST_GATHER_GYLIA_FISH_III("Mini-Quest - Gather Gylia Fish III"),
MINIQUEST_GATHER_SORGHUM_III("Mini-Quest - Gather Sorghum III"),
MINIQUEST_GATHER_SORGHUM_IV("Mini-Quest - Gather Sorghum IV"),
MINIQUEST_GATHER_MOLTEN_ORE_IV("Mini-Quest - Gather Molten Ore IV"),
MINIQUEST_GATHER_MOLTEN_ORE("Mini-Quest - Gather Molten Ore"),
MINIQUEST_GATHER_MOLTEN_ORE_II("Mini-Quest - Gather Molten Ore II"),
MINIQUEST_GATHER_MOLTEN_EEL("Mini-Quest - Gather Molten Eel"),
MINIQUEST_GATHER_MOLTEN_EEL_II("Mini-Quest - Gather Molten Eel II"),
MINIQUEST_GATHER_MOLTEN_EEL_III("Mini-Quest - Gather Molten Eel III"),
MINIQUEST_GATHER_MOLTEN_EEL_IV("Mini-Quest - Gather Molten Eel IV");

  private String key;
  /**
@param wynnApiKey how it is defined in the wynn api.
  
  */
  Quests(String wynnApiKey) {
    this.key = wynnApiKey;
  }
  public String getKey() {
    return this.key;
  }
  
}