package com.trig.api.dungeons;


enum Dungeons {

  DECREPIT_SEWERS,
  INFESTED_PIT,
  LOST_SANCTUARY,
  UNDERWORLD_CRYPT,
  SAND_SWEPT_TOMB,
  ICE_BARROWS,
  UNDERGROWTH_RUINS,
  GALLLEONS_GRAVEYARD,
  FALLEN_FACTORY,
  ELDRITCH_OUTLOOK,
  // corrupted
  CORRUPTED_DECREPIT_SEWERS,
  CORRUPTED_INFESTED_PIT,
  CORRUPTED_LOST_SANCTUARY,
  CORRUPTED_UNDERWORLD_CRYPT,
  CORRUPTED_SAND_SWEPT_TOMB,
  CORRUPTED_ICE_BARROWS,
  CORRUPTED_UNDERGROWTH_RUINS;
  
}